# Generated by Django 6.0.7 on 2026-08-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_alter_providerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
