# Generated by Django 6.0.7 on 2026-08-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_image_alter_servicecategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(blank=True, default='home_repair_service', max_length=100),
        ),
    ]
