# Generated by Django 6.0.7 on 2026-08-07 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicecategory_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['created_at']},
        ),
    ]
